package com.hdfc.transactionservice.transaction.dto;

import jakarta.validation.constraints.*;
import lombok.Data;

import java.math.BigDecimal;

/**
 * Request DTO for initiating a fund transfer.
 *
 * <p>Used for INTERNAL_TRANSFER transactions — transfers between
 * two accounts within HDFC NetBanking. The authenticated user's
 * ID is extracted from the JWT, not from this request body.
 *
 * <p>The transactionReference is generated by the client and sent
 * with the request. This enables idempotency — if the same request
 * is retried, we detect the duplicate reference and return the
 * existing result without reprocessing.
 */
@Data
public class InitiateTransferRequest {

    /**
     * The account ID to debit (source of funds).
     * Must belong to the authenticated user — enforced in service layer.
     */
    @NotNull(message = "Source account ID is required")
    private Long sourceAccountId;

    /**
     * The account ID to credit (destination of funds).
     * Must be different from sourceAccountId.
     */
    @NotNull(message = "Destination account ID is required")
    private Long destinationAccountId;

    /**
     * The amount to transfer. Must be positive and non-zero.
     * Maximum 15 digits before decimal — matches DECIMAL(19,4) storage
     * minus the 4 decimal places.
     */
    @NotNull(message = "Amount is required")
    @DecimalMin(value = "0.01", message = "Amount must be greater than zero")
    @Digits(integer = 15, fraction = 4,
            message = "Amount must have at most 15 integer digits " +
                    "and 4 decimal places")
    private BigDecimal amount;

    /**
     * ISO 4217 currency code. Must be exactly 3 uppercase letters.
     * Primary currency is NGN per project requirements.
     */
    @NotBlank(message = "Currency code is required")
    @Size(min = 3, max = 3, message = "Currency code must be exactly 3 characters")
    private String currencyCode;

    /**
     * Optional human-readable description of the transfer.
     * Example: "Rent payment for March 2026"
     */
    @Size(max = 255, message = "Description must not exceed 255 characters")
    private String description;

    /**
     * Client-generated unique reference for idempotency.
     * Format recommended: UUID or TXN-{UUID}.
     * If a transaction with this reference already exists,
     * the existing result is returned — no double processing.
     */
    @NotBlank(message = "Transaction reference is required")
    @Size(max = 50, message = "Transaction reference must not exceed 50 characters")
    private String transactionReference;
}