package com.hdfc.transactionservice.transaction.dto;

import jakarta.validation.constraints.*;
import lombok.Data;

import java.math.BigDecimal;

/**
 * Request DTO for initiating a Paystack payment.
 *
 * <p>Paystack processes payments in kobo (NGN subunit).
 * The amount here is in NGN — conversion to kobo is handled
 * in the PaystackClient before calling the Paystack API
 * (multiply by 100).
 *
 * <p>Paystack generates its own payment reference on initialisation.
 * The transactionReference here is our internal reference for
 * idempotency — both are stored on the Transaction record.
 */
@Data
public class InitiatePaystackPaymentRequest {

    /**
     * The account ID to credit when Paystack confirms payment.
     * Must belong to the authenticated user.
     */
    @NotNull(message = "Destination account ID is required")
    private Long destinationAccountId;

    /**
     * Amount in NGN. Paystack only supports NGN in sandbox mode.
     * Converted to kobo (x100) before calling Paystack API.
     */
    @NotNull(message = "Amount is required")
    @DecimalMin(value = "0.01", message = "Amount must be greater than zero")
    @Digits(integer = 15, fraction = 4,
            message = "Amount must have at most 15 integer digits " +
                    "and 4 decimal places")
    private BigDecimal amount;

    /**
     * Customer email address passed to Paystack for payment
     * initialisation. Paystack sends payment receipt to this email.
     * Must match the authenticated user's email — enforced in
     * service layer.
     */
    @NotBlank(message = "Email is required")
    @Email(message = "Email must be valid")
    private String email;

    /**
     * Optional description shown on the Paystack payment page.
     */
    @Size(max = 255, message = "Description must not exceed 255 characters")
    private String description;

    /**
     * Client-generated internal reference for idempotency.
     * Distinct from the Paystack reference (generated by Paystack).
     */
    @NotBlank(message = "Transaction reference is required")
    @Size(max = 50,
            message = "Transaction reference must not exceed 50 characters")
    private String transactionReference;
}