package com.hdfc.userservice.twofa.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * Inbound DTO carrying the TOTP code submitted by the user during
 * 2FA setup verification or login 2FA verification.
 *
 * <p>Used for two endpoints:
 * <ul>
 *   <li>{@code POST /api/v1/2fa/verify} — completes 2FA setup</li>
 *   <li>{@code POST /api/v1/auth/2fa/validate} — validates login 2FA</li>
 * </ul>
 *
 * <p>Immutable after deserialization — no setters.
 */
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TwoFactorVerifyRequest {

    /**
     * The 6-digit TOTP code generated by the user's authenticator app.
     * Valid for a 30-second time window per RFC 6238.
     * Must be exactly 6 digits — no letters or special characters.
     */
    @NotBlank(message = "OTP code is required")
    @Pattern(
            regexp = "^[0-9]{6}$",
            message = "OTP code must be exactly 6 digits"
    )
    private String code;
}